[project]
    dependencies = [
        "django-crispy-forms>=2.4",
        "django-environ>=0.12.0",
        "django>=5.2.4",
        "fontawesomefree>=6.6.0",
        "pillow>=11.3.0",
]
    name = "proyectofinaldjango"
    requires-python = ">=3.13"
    version = "0.1.0"
